version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  webapp_folder: .\NackowskisMax
  webapp_proj: $(webapp_folder)\NackowskisMax.csproj
  webapp_package: NackowskisMax.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  test_proj: .\XUnitTestProject1\NackowskisMaxTest.csproj

before_build:
  - ps: dotnet restore

build:
  verbosity: minimal
  project: NackowskisMax.sln

after_build:
  - ps: .\package.ps1 -projectPath $env:webapp_proj -packageName $env:webapp_package -absoluteRepoDirectory $env:APPVEYOR_BUILD_FOLDER

artifacts:
  - path: '**\$(webapp_package).zip'

test: off
test_script:
  - ps: .\test_script.ps1 $env:test_proj

deploy:
  - provider: WebDeploy
    name: Production
    server: https://$(azure_website).scm.azurewebsites.net:443/msdeploy.axd?site=$(azure_website)
    website: $(azure_website)
    username: $(azure_username)
    password: $(azure_password)
    artifact: $(webapp1_package).zip
    aspnet_core: true
    aspnet_core_force_restart: true
    app_offline: true
    remove_files: true
    do_not_use_checksum: true
    on:
      branch: master
  