version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  webapp_folder: .\NackowskisMax
  webapp_proj: $(webapp_folder)\NackowskisMax.csproj
  webapp_package: NackowskisMax.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  test_proj: .\XUnitTestProject1\NackowskisMaxTest.csproj

before_build:
  - ps: dotnet restore

build:
  verbosity: minimal
  project: NackowskisMax.sln

after_build:
  - ps: .\package.ps1 -projectPath $env:webapp_proj -packageName $env:webapp_package -absoluteRepoDirectory $env:APPVEYOR_BUILD_FOLDER

artifacts:
  - path: '**\$(webapp_package).zip'

test: off
test_script:
  - ps: .\test_script.ps1 $env:test_proj
  